import { type ChatMessage, type LMClient } from './lmClient';

/**
 * A TypeScript implementation of the core DSPy ideas, faithful to the real
 * framework so that what you learn here transfers directly.
 *
 * What is reproduced exactly:
 *  - Signatures: typed input and output fields plus a natural-language objective.
 *  - The ChatAdapter prompt format, including the [[ ## field ## ]] markers.
 *  - BootstrapFewShot: run the program, keep the traces that pass the metric,
 *    and reuse those as demonstrations.
 *  - COPRO-style instruction search: have the model propose new instructions,
 *    score each on real data, keep the winner.
 *  - MIPRO-style joint search over instruction and demonstration combinations.
 *
 * This is a reimplementation, not a binding to the Python package. The Export
 * tab emits the equivalent real DSPy program so a run can be reproduced there.
 */

export interface Field {
  name: string;
  desc: string;
}

export interface Signature {
  name: string;
  instructions: string;
  inputs: Field[];
  outputs: Field[];
}

export interface Example {
  id: string;
  inputs: Record<string, string>;
  outputs: Record<string, string>;
}

export interface Demo {
  inputs: Record<string, string>;
  outputs: Record<string, string>;
  /** True when this demo was generated by the model rather than hand-labelled. */
  bootstrapped: boolean;
}

export interface Program {
  signature: Signature;
  demos: Demo[];
  /** Chain of thought prepends a reasoning field the model must fill first. */
  cot: boolean;
}

export interface Prediction {
  outputs: Record<string, string>;
  raw: string;
  messages: ChatMessage[];
  error?: string;
}

const REASONING: Field = {
  name: 'reasoning',
  desc: 'Think step by step before answering.',
};

export function effectiveOutputs(p: Program): Field[] {
  return p.cot ? [REASONING, ...p.signature.outputs] : p.signature.outputs;
}

/* ------------------------------------------------------------- adapter -- */

function fieldList(fields: Field[]): string {
  return fields.map((f, i) => `${i + 1}. \`${f.name}\` (str): ${f.desc}`).join('\n');
}

function fieldBlock(name: string, value: string): string {
  return `[[ ## ${name} ## ]]\n${value}`;
}

/** The system prompt, in the same shape DSPy ChatAdapter produces. */
export function buildSystemMessage(p: Program): string {
  const outs = effectiveOutputs(p);
  const structure = [
    ...p.signature.inputs.map((f) => fieldBlock(f.name, `{${f.name}}`)),
    ...outs.map((f) => fieldBlock(f.name, `{${f.name}}`)),
    '[[ ## completed ## ]]',
  ].join('\n\n');

  return [
    'Your input fields are:',
    fieldList(p.signature.inputs),
    '',
    'Your output fields are:',
    fieldList(outs),
    '',
    'All interactions will be structured in the following way, with the appropriate values filled in.',
    '',
    structure,
    '',
    `In adhering to this structure, your objective is:`,
    `        ${p.signature.instructions}`,
  ].join('\n');
}

function userTurn(p: Program, inputs: Record<string, string>): string {
  const blocks = p.signature.inputs.map((f) => fieldBlock(f.name, inputs[f.name] ?? ''));
  const outs = effectiveOutputs(p);
  blocks.push(
    `Respond with the corresponding output fields, starting with the field ` +
      outs.map((f) => `\`[[ ## ${f.name} ## ]]\``).join(', then ') +
      `, and then ending with the marker for \`[[ ## completed ## ]]\`.`,
  );
  return blocks.join('\n\n');
}

function assistantTurn(p: Program, outputs: Record<string, string>): string {
  const outs = effectiveOutputs(p);
  return (
    outs.map((f) => fieldBlock(f.name, outputs[f.name] ?? '')).join('\n\n') + '\n\n[[ ## completed ## ]]'
  );
}

/** Full message list for one call, demos included. */
export function buildMessages(p: Program, inputs: Record<string, string>): ChatMessage[] {
  const msgs: ChatMessage[] = [{ role: 'system', content: buildSystemMessage(p) }];
  for (const d of p.demos) {
    msgs.push({ role: 'user', content: userTurn(p, d.inputs) });
    msgs.push({ role: 'assistant', content: assistantTurn(p, d.outputs) });
  }
  msgs.push({ role: 'user', content: userTurn(p, inputs) });
  return msgs;
}

/** Pull `[[ ## field ## ]]` sections back out of the model response. */
export function parseResponse(p: Program, raw: string): Record<string, string> {
  const outs = effectiveOutputs(p);
  const result: Record<string, string> = {};
  const re = /\[\[ ## ([a-zA-Z0-9_]+) ## \]\]/g;
  const marks: { name: string; start: number; end: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    marks.push({ name: m[1], start: m.index, end: m.index + m[0].length });
  }
  if (marks.length === 0) {
    // Model ignored the format. Fall back to giving the whole reply to the
    // first non-reasoning output field, which is what DSPy does too.
    const target = outs.find((f) => f.name !== 'reasoning') ?? outs[0];
    if (target) result[target.name] = raw.trim();
    return result;
  }
  for (let i = 0; i < marks.length; i++) {
    const cur = marks[i];
    if (cur.name === 'completed') continue;
    const stop = i + 1 < marks.length ? marks[i + 1].start : raw.length;
    result[cur.name] = raw.slice(cur.end, stop).trim();
  }
  return result;
}

export async function runProgram(
  client: LMClient,
  p: Program,
  inputs: Record<string, string>,
  tag = 'predict',
  signal?: AbortSignal,
): Promise<Prediction> {
  const messages = buildMessages(p, inputs);
  try {
    const raw = await client.complete(messages, tag, signal);
    return { outputs: parseResponse(p, raw), raw, messages };
  } catch (err) {
    return {
      outputs: {},
      raw: '',
      messages,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/* -------------------------------------------------------------- metrics -- */

export type Metric = (ex: Example, pred: Prediction) => number;

export interface MetricDef {
  id: string;
  label: string;
  blurb: string;
  fn: (field: string) => Metric;
}

const norm = (s: string) =>
  (s ?? '')
    .toLowerCase()
    .replace(/[.,!?;:"']/g, '')
    .replace(/\b(a|an|the)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

export const METRICS: MetricDef[] = [
  {
    id: 'exact',
    label: 'Exact match',
    blurb: 'Scores 1 only when the answer matches the label after lowercasing and stripping punctuation. Strict and unforgiving.',
    fn: (field) => (ex, pred) => (norm(pred.outputs[field]) === norm(ex.outputs[field]) ? 1 : 0),
  },
  {
    id: 'contains',
    label: 'Contains answer',
    blurb: 'Scores 1 when the gold answer appears anywhere in the prediction. Tolerant of a chatty model.',
    fn: (field) => (ex, pred) => {
      const g = norm(ex.outputs[field]);
      const p = norm(pred.outputs[field]);
      return g.length > 0 && p.includes(g) ? 1 : 0;
    },
  },
  {
    id: 'f1',
    label: 'Token F1',
    blurb: 'Word-overlap score between prediction and label. Gives partial credit, which makes optimizer progress easier to see.',
    fn: (field) => (ex, pred) => {
      const g = norm(ex.outputs[field]).split(' ').filter(Boolean);
      const p = norm(pred.outputs[field]).split(' ').filter(Boolean);
      if (g.length === 0 || p.length === 0) return 0;
      const counts = new Map<string, number>();
      for (const w of g) counts.set(w, (counts.get(w) ?? 0) + 1);
      let overlap = 0;
      for (const w of p) {
        const c = counts.get(w) ?? 0;
        if (c > 0) {
          overlap++;
          counts.set(w, c - 1);
        }
      }
      if (overlap === 0) return 0;
      const precision = overlap / p.length;
      const recall = overlap / g.length;
      return (2 * precision * recall) / (precision + recall);
    },
  },
  {
    id: 'numeric',
    label: 'Numeric match',
    blurb: 'Extracts the last number from each side and compares them. The right choice for arithmetic tasks.',
    fn: (field) => (ex, pred) => {
      const last = (s: string) => {
        const all = (s ?? '').match(/-?\d+(?:\.\d+)?/g);
        return all ? parseFloat(all[all.length - 1]) : NaN;
      };
      const a = last(pred.outputs[field]);
      const b = last(ex.outputs[field]);
      return Number.isFinite(a) && Number.isFinite(b) && Math.abs(a - b) < 1e-6 ? 1 : 0;
    },
  },
];

/* ----------------------------------------------------------- evaluation -- */

export interface EvalResult {
  example: Example;
  prediction: Prediction;
  score: number;
}

export interface EvalSummary {
  score: number;
  results: EvalResult[];
  promptTokens: number;
  completionTokens: number;
  calls: number;
  wallMs: number;
}

export async function evaluate(
  client: LMClient,
  program: Program,
  examples: Example[],
  metric: Metric,
  opts: {
    tag?: string;
    concurrency?: number;
    onProgress?: (done: number, total: number, r: EvalResult) => void;
    signal?: AbortSignal;
  } = {},
): Promise<EvalSummary> {
  const { tag = 'eval', concurrency = 4, onProgress, signal } = opts;
  const t0 = performance.now();
  const before = { p: client.totalPromptTokens, c: client.totalCompletionTokens, n: client.calls.length };
  const results: EvalResult[] = new Array(examples.length);
  let done = 0;
  let cursor = 0;

  const worker = async () => {
    for (;;) {
      const i = cursor++;
      if (i >= examples.length) return;
      if (signal?.aborted) return;
      const ex = examples[i];
      const pred = await runProgram(client, program, ex.inputs, tag, signal);
      const score = pred.error ? 0 : metric(ex, pred);
      const r = { example: ex, prediction: pred, score };
      results[i] = r;
      done++;
      onProgress?.(done, examples.length, r);
    }
  };

  await Promise.all(Array.from({ length: Math.min(concurrency, examples.length) }, worker));
  const filled = results.filter(Boolean);
  return {
    score: filled.length ? filled.reduce((a, r) => a + r.score, 0) / filled.length : 0,
    results: filled,
    promptTokens: client.totalPromptTokens - before.p,
    completionTokens: client.totalCompletionTokens - before.c,
    calls: client.calls.length - before.n,
    wallMs: performance.now() - t0,
  };
}

/* ----------------------------------------------------------- optimizers -- */

export type OptimizerId = 'labeled' | 'bootstrap' | 'copro' | 'mipro';

export interface OptimizerInfo {
  id: OptimizerId;
  label: string;
  short: string;
  blurb: string;
  changes: string;
}

export const OPTIMIZERS: OptimizerInfo[] = [
  {
    id: 'labeled',
    label: 'LabeledFewShot',
    short: 'Pick k labelled examples and paste them into the prompt.',
    blurb:
      'The baseline. No model calls are needed to build it: it simply selects k examples from your training set and shows them to the model as demonstrations. Often a surprisingly strong jump over zero-shot.',
    changes: 'Demonstrations only',
  },
  {
    id: 'bootstrap',
    label: 'BootstrapFewShot',
    short: 'Let the model solve training examples, keep the ones it got right.',
    blurb:
      'Runs the current program over the training set and records the full trace for every example the metric marks correct. Those self-generated traces become the demonstrations. Crucially, with chain of thought enabled the demos now contain reasoning the model actually produced, which is usually better matched to it than anything written by hand.',
    changes: 'Demonstrations only',
  },
  {
    id: 'copro',
    label: 'COPRO',
    short: 'Ask the model to rewrite its own instructions, keep whatever scores best.',
    blurb:
      'Coordinate-ascent over the instruction string. At each round the model is shown the instructions tried so far along with their scores and asked to propose better ones. Every candidate is scored on real data; only measured improvements survive.',
    changes: 'Instructions only',
  },
  {
    id: 'mipro',
    label: 'MIPRO (light)',
    short: 'Search instruction and demonstration combinations together.',
    blurb:
      'Generates a pool of candidate instructions and a pool of bootstrapped demonstration sets, then searches over combinations of the two, scoring each on a minibatch. Instructions and demos interact, so tuning them jointly beats tuning either alone.',
    changes: 'Instructions and demonstrations',
  },
];

export interface OptimizerEvent {
  kind: 'info' | 'candidate' | 'best' | 'trace' | 'error';
  msg: string;
  score?: number;
  detail?: string;
}

export interface OptimizeOpts {
  trainset: Example[];
  valset: Example[];
  metric: Metric;
  maxDemos: number;
  candidates: number;
  rounds: number;
  minibatch: number;
  onEvent?: (e: OptimizerEvent) => void;
  signal?: AbortSignal;
}

export interface Candidate {
  label: string;
  program: Program;
  score: number;
}

export interface OptimizeResult {
  program: Program;
  baselineScore: number;
  optimizedScore: number;
  events: OptimizerEvent[];
  tried: { instructions: string; demoCount: number; score: number }[];
  /**
   * Every candidate that was built and scored, winner or not. Kept so the UI
   * can show what an optimizer tried, including work that did not pay off.
   */
  candidatePrograms: Candidate[];
}

function shuffled<T>(arr: T[], rand: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Deterministic, so a demo run reproduces exactly. */
function rng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Run the program over the training set and keep the traces it got right.
 * This is the heart of BootstrapFewShot.
 */
async function bootstrapDemos(
  client: LMClient,
  program: Program,
  opts: OptimizeOpts,
  limit: number,
  emit: (e: OptimizerEvent) => void,
  seed = 1,
): Promise<Demo[]> {
  const demos: Demo[] = [];
  const pool = shuffled(opts.trainset, rng(seed));
  for (const ex of pool) {
    if (demos.length >= limit) break;
    if (opts.signal?.aborted) break;
    const pred = await runProgram(client, program, ex.inputs, 'bootstrap', opts.signal);
    if (pred.error) {
      emit({ kind: 'error', msg: `call failed on ${ex.id}: ${pred.error}` });
      continue;
    }
    const score = opts.metric(ex, pred);
    if (score >= 1) {
      // Keep the model-generated fields, but pin the gold label so the demo
      // teaches the correct answer rather than a lucky one.
      const outputs: Record<string, string> = { ...pred.outputs, ...ex.outputs };
      demos.push({ inputs: ex.inputs, outputs, bootstrapped: true });
      emit({
        kind: 'trace',
        msg: `kept trace for ${ex.id} (metric ${score.toFixed(2)})`,
        score,
        detail: effectiveOutputs(program)
          .map((f) => `${f.name}: ${outputs[f.name] ?? ''}`)
          .join('\n'),
      });
    } else {
      emit({ kind: 'info', msg: `discarded ${ex.id} (metric ${score.toFixed(2)})`, score });
    }
  }
  return demos;
}

/** Ask the model to propose better instruction strings for its own task. */
async function proposeInstructions(
  client: LMClient,
  program: Program,
  history: { instructions: string; score: number }[],
  n: number,
  opts: OptimizeOpts,
): Promise<string[]> {
  const task = [
    `You are optimizing the instruction string for a language model program.`,
    ``,
    `The program takes these inputs: ${program.signature.inputs.map((f) => f.name).join(', ')}`,
    `and must produce these outputs: ${program.signature.outputs.map((f) => f.name).join(', ')}.`,
    ``,
    `Instructions tried so far, with their measured scores:`,
    ...history
      .slice()
      .sort((a, b) => a.score - b.score)
      .map((h) => `  score ${h.score.toFixed(3)}: ${h.instructions}`),
    ``,
    `Propose ${n} new instruction strings that should score higher.`,
    `Be specific about the format and reasoning the task requires.`,
    `Return one per line, numbered, with no other commentary.`,
  ].join('\n');

  try {
    const raw = await client.complete(
      [{ role: 'user', content: task }],
      'propose-instructions',
      opts.signal,
    );
    return raw
      .split('\n')
      .map((l) => l.replace(/^\s*\d+[.)]\s*/, '').trim())
      .filter((l) => l.length > 12)
      .slice(0, n);
  } catch {
    return [];
  }
}

export async function optimize(
  client: LMClient,
  base: Program,
  id: OptimizerId,
  opts: OptimizeOpts,
): Promise<OptimizeResult> {
  const events: OptimizerEvent[] = [];
  const tried: { instructions: string; demoCount: number; score: number }[] = [];
  const candidatePrograms: Candidate[] = [];
  const emit = (e: OptimizerEvent) => {
    events.push(e);
    opts.onEvent?.(e);
  };
  const record = (label: string, program: Program, score: number) => {
    candidatePrograms.push({ label, program, score });
    tried.push({ instructions: program.signature.instructions, demoCount: program.demos.length, score });
  };

  emit({ kind: 'info', msg: `scoring the unoptimized program on ${opts.valset.length} held-out examples` });
  const baseEval = await evaluate(client, base, opts.valset, opts.metric, {
    tag: 'baseline',
    signal: opts.signal,
  });
  emit({ kind: 'best', msg: `baseline score`, score: baseEval.score });
  record('Unoptimized baseline', base, baseEval.score);

  let best: Program = { ...base, demos: [...base.demos] };
  let bestScore = baseEval.score;

  const scoreOn = async (p: Program, set: Example[], tag: string) => {
    const r = await evaluate(client, p, set, opts.metric, { tag, signal: opts.signal });
    return r.score;
  };

  if (id === 'labeled') {
    const rand = rng(11);
    const picked = shuffled(opts.trainset, rand).slice(0, opts.maxDemos);
    const cand: Program = {
      ...base,
      demos: picked.map((e) => ({ inputs: e.inputs, outputs: e.outputs, bootstrapped: false })),
    };
    emit({ kind: 'info', msg: `selected ${picked.length} labelled examples as demonstrations` });
    const s = await scoreOn(cand, opts.valset, 'labeled');
    record(`LabeledFewShot (${cand.demos.length} demos)`, cand, s);
    emit({ kind: 'candidate', msg: `LabeledFewShot with ${picked.length} demos`, score: s });
    if (s > bestScore) {
      best = cand;
      bestScore = s;
    }
  }

  if (id === 'bootstrap') {
    emit({ kind: 'info', msg: `running the program over the training set to harvest correct traces` });
    const demos = await bootstrapDemos(client, base, opts, opts.maxDemos, emit);
    emit({ kind: 'info', msg: `collected ${demos.length} passing traces` });
    if (demos.length === 0) {
      emit({ kind: 'error', msg: 'no training example passed the metric, so there is nothing to bootstrap from. Try a looser metric or an easier task.' });
    } else {
      const cand: Program = { ...base, demos };
      const s = await scoreOn(cand, opts.valset, 'bootstrap');
      record(`BootstrapFewShot (${demos.length} demos)`, cand, s);
      emit({ kind: 'candidate', msg: `BootstrapFewShot with ${demos.length} self-generated demos`, score: s });
      if (s > bestScore) {
        best = cand;
        bestScore = s;
      }
    }
  }

  if (id === 'copro') {
    const history = [{ instructions: base.signature.instructions, score: bestScore }];
    for (let round = 0; round < opts.rounds; round++) {
      if (opts.signal?.aborted) break;
      emit({ kind: 'info', msg: `round ${round + 1}: asking the model for ${opts.candidates} new instruction candidates` });
      const proposals = await proposeInstructions(client, best, history, opts.candidates, opts);
      if (proposals.length === 0) {
        emit({ kind: 'error', msg: 'the model returned no usable proposals' });
        break;
      }
      for (const text of proposals) {
        if (opts.signal?.aborted) break;
        const cand: Program = { ...best, signature: { ...best.signature, instructions: text } };
        const s = await scoreOn(cand, opts.valset, 'copro');
        history.push({ instructions: text, score: s });
        record('COPRO instruction candidate', cand, s);
        emit({ kind: 'candidate', msg: text, score: s });
        if (s > bestScore) {
          bestScore = s;
          best = cand;
          emit({ kind: 'best', msg: `new best instruction`, score: s, detail: text });
        }
      }
    }
  }

  if (id === 'mipro') {
    emit({ kind: 'info', msg: 'building a pool of demonstration sets' });
    const demoSets: Demo[][] = [[]];
    for (let i = 0; i < Math.min(3, opts.candidates); i++) {
      if (opts.signal?.aborted) break;
      const d = await bootstrapDemos(client, base, opts, opts.maxDemos, emit, 7 + i * 13);
      if (d.length) demoSets.push(d);
    }
    emit({ kind: 'info', msg: `${demoSets.length} demonstration sets available` });

    emit({ kind: 'info', msg: 'proposing instruction candidates' });
    const instr = [
      base.signature.instructions,
      ...(await proposeInstructions(client, base, [{ instructions: base.signature.instructions, score: bestScore }], opts.candidates, opts)),
    ];
    emit({ kind: 'info', msg: `${instr.length} instruction candidates available` });

    const rand = rng(23);
    const mini = shuffled(opts.valset, rand).slice(0, Math.max(3, Math.min(opts.minibatch, opts.valset.length)));
    const combos: { i: string; d: Demo[] }[] = [];
    for (const i of instr) for (const d of demoSets) combos.push({ i, d });
    const budget = Math.min(combos.length, Math.max(4, opts.candidates * 2));
    emit({ kind: 'info', msg: `searching ${budget} of ${combos.length} combinations on a ${mini.length}-example minibatch` });

    let bestCombo: { i: string; d: Demo[] } | null = null;
    let bestMini = -1;
    for (const c of shuffled(combos, rand).slice(0, budget)) {
      if (opts.signal?.aborted) break;
      const cand: Program = {
        ...base,
        signature: { ...base.signature, instructions: c.i },
        demos: c.d,
      };
      const s = await scoreOn(cand, mini, 'mipro-mini');
      record(`MIPRO combo (${c.d.length} demos)`, cand, s);
      emit({ kind: 'candidate', msg: `${c.d.length} demos | ${c.i.slice(0, 90)}`, score: s });
      if (s > bestMini) {
        bestMini = s;
        bestCombo = c;
      }
    }

    if (bestCombo) {
      const cand: Program = {
        ...base,
        signature: { ...base.signature, instructions: bestCombo.i },
        demos: bestCombo.d,
      };
      emit({ kind: 'info', msg: 'scoring the best combination on the full validation set' });
      const s = await scoreOn(cand, opts.valset, 'mipro-final');
      record('MIPRO best combination (full validation)', cand, s);
      emit({ kind: 'candidate', msg: 'best combination, full validation', score: s });
      if (s > bestScore) {
        bestScore = s;
        best = cand;
      }
    }
  }

  emit({ kind: 'best', msg: 'optimization finished', score: bestScore });
  return {
    program: best,
    baselineScore: baseEval.score,
    optimizedScore: bestScore,
    events,
    tried,
    candidatePrograms,
  };
}
