import { buildMessages, buildSystemMessage, effectiveOutputs, type Example, type Program } from './dspy';
import type { LMConfig } from './lmClient';
import type { TaskDef } from './tasks';

/**
 * Emits the equivalent program for the real Python DSPy package, so a run that
 * was explored here can be reproduced with the genuine framework.
 */

const py = (s: string) => JSON.stringify(s);

function pyExamples(name: string, examples: Example[], inputKeys: string[]): string {
  const rows = examples.map((e) => {
    const kv = [
      ...Object.entries(e.inputs).map(([k, v]) => `${k}=${py(v)}`),
      ...Object.entries(e.outputs).map(([k, v]) => `${k}=${py(v)}`),
    ].join(', ');
    return `    dspy.Example(${kv}).with_inputs(${inputKeys.map(py).join(', ')}),`;
  });
  return `${name} = [\n${rows.join('\n')}\n]`;
}

const METRIC_BODY: Record<string, (field: string) => string> = {
  exact: (f) => `    return _norm(getattr(pred, ${py(f)}, "")) == _norm(example.${f})`,
  contains: (f) =>
    `    gold = _norm(example.${f})\n    got = _norm(getattr(pred, ${py(f)}, ""))\n    return len(gold) > 0 and gold in got`,
  f1: (f) =>
    `    gold = _norm(example.${f}).split()\n` +
    `    got = _norm(getattr(pred, ${py(f)}, "")).split()\n` +
    `    if not gold or not got:\n        return 0.0\n` +
    `    common = Counter(gold) & Counter(got)\n` +
    `    overlap = sum(common.values())\n` +
    `    if overlap == 0:\n        return 0.0\n` +
    `    precision = overlap / len(got)\n    recall = overlap / len(gold)\n` +
    `    return 2 * precision * recall / (precision + recall)`,
  numeric: (f) =>
    `    a = _last_number(getattr(pred, ${py(f)}, ""))\n    b = _last_number(example.${f})\n` +
    `    return a is not None and b is not None and abs(a - b) < 1e-6`,
};

const OPTIMIZER_PY: Record<string, (maxDemos: number, candidates: number) => string> = {
  labeled: (d) =>
    `from dspy.teleprompt import LabeledFewShot\n\noptimizer = LabeledFewShot(k=${d})\ncompiled = optimizer.compile(program, trainset=trainset)`,
  bootstrap: (d) =>
    `from dspy.teleprompt import BootstrapFewShot\n\noptimizer = BootstrapFewShot(\n    metric=metric,\n    max_bootstrapped_demos=${d},\n    max_labeled_demos=${d},\n)\ncompiled = optimizer.compile(program, trainset=trainset)`,
  copro: (_d, c) =>
    `from dspy.teleprompt import COPRO\n\noptimizer = COPRO(metric=metric, breadth=${c}, depth=2)\ncompiled = optimizer.compile(\n    program,\n    trainset=trainset,\n    eval_kwargs=dict(num_threads=4, display_progress=True),\n)`,
  mipro: (d, c) =>
    `from dspy.teleprompt import MIPROv2\n\noptimizer = MIPROv2(metric=metric, auto="light")\ncompiled = optimizer.compile(\n    program,\n    trainset=trainset,\n    valset=valset,\n    max_bootstrapped_demos=${d},\n    num_trials=${Math.max(6, c * 2)},\n    requires_permission_to_run=False,\n)`,
};

export interface ExportOpts {
  task: TaskDef;
  program: Program;
  lm: LMConfig;
  optimizerId: string;
  metricId: string;
  metricField: string;
  trainset: Example[];
  valset: Example[];
  maxDemos: number;
  candidates: number;
}

export function toPython(o: ExportOpts): string {
  const sig = o.program.signature;
  const inputKeys = sig.inputs.map((f) => f.name);
  const metricFn = METRIC_BODY[o.metricId] ?? METRIC_BODY.exact;
  const optim = (OPTIMIZER_PY[o.optimizerId] ?? OPTIMIZER_PY.bootstrap)(o.maxDemos, o.candidates);
  const moduleCall = o.program.cot ? 'dspy.ChainOfThought' : 'dspy.Predict';
  const needsCounter = o.metricId === 'f1';

  return `"""
${sig.name} -- generated by Glassbox.

Reproduces, with the real DSPy package, the run you just performed in the
browser. Install with:  pip install -U dspy

The API key is read from the environment rather than hard-coded.
"""

import os
import re
${needsCounter ? 'from collections import Counter\n' : ''}import dspy

# ---------------------------------------------------------------- model ----

lm = dspy.LM(
    ${py(`openai/${o.lm.model}`)},
    api_base=${py(o.lm.baseUrl)},
    api_key=os.environ.get("GLASSBOX_API_KEY", ""),
    temperature=${o.lm.temperature},
    max_tokens=${o.lm.maxTokens},
)
dspy.configure(lm=lm)

# ------------------------------------------------------------ signature ----

class ${sig.name}(dspy.Signature):
    """${sig.instructions.replace(/"""/g, "'''")}"""

${sig.inputs.map((f) => `    ${f.name}: str = dspy.InputField(desc=${py(f.desc)})`).join('\n')}
${sig.outputs.map((f) => `    ${f.name}: str = dspy.OutputField(desc=${py(f.desc)})`).join('\n')}


program = ${moduleCall}(${sig.name})

# ------------------------------------------------------------------ data ----

${pyExamples('trainset', o.trainset, inputKeys)}

${pyExamples('valset', o.valset, inputKeys)}

# ---------------------------------------------------------------- metric ----

def _norm(s):
    s = (s or "").lower()
    s = re.sub(r"[.,!?;:\\"']", "", s)
    s = re.sub(r"\\b(a|an|the)\\b", " ", s)
    return re.sub(r"\\s+", " ", s).strip()

${
  o.metricId === 'numeric'
    ? `def _last_number(s):
    found = re.findall(r"-?\\d+(?:\\.\\d+)?", s or "")
    return float(found[-1]) if found else None

`
    : ''
}def metric(example, pred, trace=None):
${metricFn(o.metricField)}

# ------------------------------------------------------------- baseline ----

evaluate = dspy.Evaluate(devset=valset, metric=metric, num_threads=4, display_progress=True)
print("before:", evaluate(program))

# ------------------------------------------------------------- optimize ----

${optim}

print("after: ", evaluate(compiled))

# Inspect what actually changed in the prompt.
dspy.inspect_history(n=1)

compiled.save("${sig.name.toLowerCase()}_compiled.json")
print("saved to ${sig.name.toLowerCase()}_compiled.json")
`;
}

/** The literal prompt the optimized program sends, ready to paste anywhere. */
export function toPromptText(program: Program, sampleInputs: Record<string, string>): string {
  const msgs = buildMessages(program, sampleInputs);
  return msgs
    .map((m) => `--- ${m.role.toUpperCase()} ---\n${m.content}`)
    .join('\n\n');
}

export function toSystemPrompt(program: Program): string {
  return buildSystemMessage(program);
}

/** Portable JSON of everything the optimizer decided. */
export function toJSON(program: Program): string {
  return JSON.stringify(
    {
      signature: {
        name: program.signature.name,
        instructions: program.signature.instructions,
        inputs: program.signature.inputs,
        outputs: effectiveOutputs(program),
      },
      chain_of_thought: program.cot,
      demos: program.demos,
    },
    null,
    2,
  );
}
